apiVersion: v1
kind: Service
metadata:
  name: weather-app-service
spec:
  type: LoadBalancer  # Use 'NodePort' if you prefer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: weather-app
